apiVersion: apps/v1
kind: Deployment
metadata:
  name: amcdan10-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amcdan10-app
  template:
    metadata:
      labels:
        app: amcdan10-app
    spec:
      containers:
        - name: amcdan10-app
          image: amcdan10-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: amcdan10-app
spec:
  selector:
    app: amcdan10-app
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
